services:
  #Minio-ai-stor
  aistor-minio:
    image: quay.io/minio/aistor/minio:latest
    container_name: aistor-minio-server
    command: minio server /mnt/data --console-address ":9001" --license /minio.license
    ports:
      - "9200:9000"
      - "9201:9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    volumes:
      - ./data:/mnt/data
      - ./minio.license:/minio.license

  aistor-mc:
    image: quay.io/minio/aistor/mc:latest
    container_name: aistor-mc
    depends_on:
      - aistor-minio
    volumes:
      - ./scripts/aistor:/scripts/aistor
    entrypoint: /bin/sh #To open the shell immediately
    command: -c "/scripts/aistor/init-warehouse.sh" # This will create automatic wearhouse

  # Spark
  spark:
#    image: apache/spark:4.0.0
    image: maryam811/spark:4.0.0
    container_name: spark
    working_dir: /opt/spark
    volumes:
      - ./config/spark-config/spark-defaults.conf:/opt/spark/conf/spark-defaults.conf
      - ./scripts/spark:/opt/spark/custom-scripts/
      - ./input-data:/opt/spark/data/input
      - ./mnt/spark/jobs:/opt/spark/jobs
    entrypoint: /bin/bash
    # Interactive Container
    stdin_open: true
    tty: true

 # Trino 
  trino:
    image: trinodb/trino:480
    container_name: aistor-trino
    ports:
      - "8580:8080"
    volumes:
      - ./config/trino-config/catalog:/etc/trino/catalog
    depends_on:
      - aistor-minio
    restart: unless-stopped

  # Postgres
  postgres:
    image: postgres:16
    container_name: demo-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: demo_db
    volumes:
      - ./input-data/postgres-data:/var/lib/postgresql/data

  #Airflow
  airflow-db:
    image: postgres:14
    container_name: airflow-db
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow_pwd
      POSTGRES_DB: airflow_db
    ports:
      - "5532:5432"
    volumes:
      - ./mnt/airflow/postgres_data:/var/lib/postgresql/data

  airflow:
    image: maryam811/airflow-lakehouse:2.10.5
    container_name: airflow
    depends_on:
      - airflow-db
    ports:
      - "8090:8080"
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow_pwd@airflow-db:5432/airflow_db
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"

      AIRFLOW_ADMIN_USERNAME: admin
      AIRFLOW_ADMIN_PASSWORD: admin
      AIRFLOW_ADMIN_FIRSTNAME: Admin
      AIRFLOW_ADMIN_LASTNAME: User
      AIRFLOW_ADMIN_EMAIL: admin@example.com
    volumes:
      - ./mnt/airflow/dags:/opt/airflow/dags
