spark.jars.packages org.apache.iceberg:iceberg-spark-runtime-4.0_2.13:1.10.1,org.apache.iceberg:iceberg-aws-bundle:1.10.1,org.apache.hadoop:hadoop-aws:3.3.4,org.postgresql:postgresql:42.7.4

spark.jars.ivy /tmp/.ivy2
spark.local.dir /tmp/spark-local

spark.sql.extensions org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions
spark.sql.optimizer.excludedRules org.apache.spark.sql.catalyst.optimizer.SimplifyCasts

spark.sql.catalog.aistor org.apache.iceberg.spark.SparkCatalog
spark.sql.catalog.aistor.type rest
spark.sql.catalog.aistor.uri http://aistor-minio:9000/_iceberg

spark.sql.catalog.aistor.metrics-reporter-impl org.apache.iceberg.metrics.LoggingMetricsReporter

spark.sql.catalog.aistor.rest.access-key-id minio
spark.sql.catalog.aistor.rest.secret-access-key minio123
spark.sql.catalog.aistor.rest.endpoint http://aistor-minio:9000
spark.sql.catalog.aistor.rest.auth.type sigv4
spark.sql.catalog.aistor.rest.signing-name s3tables
spark.sql.catalog.aistor.rest.signing-region local

spark.sql.catalog.aistor.s3.access-key-id minio
spark.sql.catalog.aistor.s3.secret-access-key minio123
spark.sql.catalog.aistor.s3.endpoint http://aistor-minio:9000
spark.sql.catalog.aistor.s3.path-style-access true

spark.hadoop.fs.s3a.impl org.apache.hadoop.fs.s3a.S3AFileSystem
spark.hadoop.fs.s3a.endpoint http://aistor-minio:9000
spark.hadoop.fs.s3a.access.key minio
spark.hadoop.fs.s3a.secret.key minio123
spark.hadoop.fs.s3a.aws.credentials.provider org.apache.hadoop.fs.s3a.SimpleAWSCredentialsProvider
spark.hadoop.fs.s3a.path.style.access true
spark.hadoop.fs.s3a.connection.ssl.enabled false
spark.hadoop.fs.s3a.connection.timeout 60000
spark.hadoop.fs.s3a.connection.establish.timeout 60000
spark.hadoop.fs.s3a.socket.timeout 60000
spark.hadoop.fs.s3a.connection.request.timeout 60000
spark.hadoop.fs.s3a.threads.keepalivetime 60
spark.hadoop.fs.s3a.multipart.purge.age 86400